export enum CARS_MANUFACTORY {
  TAYOTA = 'TAYOTA',
  HYUNDAY = 'HYUNDAY',
  MERCEDES_BENZ = 'MERCEDES_BENZ',
  BMW = 'BMW',
  VOLKSWAGEN = 'VOLKSWAGEN',
  KIA = 'KIA',
  FORD = 'FORD',
  LEXUS = 'LEXUS',
  CHEVROLET = 'CHEVROLET',
  OPEL = 'OPEL',
}
