export enum FORD_MODEL {
  BRONCO = 'BRONCO',
  C_MAX = 'C_MAX',
  CONNECT = 'CONNECT',
  EDGE = 'EDGE',
  ESCORT = 'ESCORT',
  EXPLORER = 'EXPLORER',
  F_150 = 'F_150',
  FIESTA = 'FIESTA',
  KUGA = 'KUGA',
  TAURUS = 'TAURUS',
}
