export enum VOLKSWAGEN_MODEL {
  ATLAS = 'ATLAS',
  CADDY = 'CADDY',
  EOS = 'EOS',
  JETTA = 'JETTA',
  MAGONATAN = 'MAGONATAN',
  POLO = 'POLO',
  TAOS = 'TAOS',
  TAYRON = 'TAYRON',
  TIGUAN = 'TIGUAN',
  TOURAN = 'TOURAN',
}
